# é…ç½®æ–‡ä»¶
# å‚è€ƒï¼š
# https://www.getzola.org/documentation/getting-started/configuration/
# https://github.com/welpo/tabi-start/blob/main/config.toml

base_url = "https://inhere.github.io"

title = "Inhere's Site"
description = "Inhere's site, blogs and project docs"
author = "Inhere"
theme = "tabi"
generate_feeds = true
compile_sass = true
minify_html = true
# ç”Ÿæˆæœç´¢ç´¢å¼•
build_search_index = false # TODO é»˜è®¤ä¸æ”¯æŒä¸­æ–‡ç´¢å¼•,æš‚æ—¶å…³é—­
default_language = "zh-Hans" # en, zh-Hans
# default_language = "zh_CN" zh, zh-CN, zh-Hans
taxonomies = [{name = "tags", feed = true}]

# [languages.zh-Hans]
# title = "æˆ‘çš„ç½‘ç«™"

# BUG å¦‚æœæ–‡ä»¶åå«æœ‰ . (eg: some-v0.5.2.en.md) ä¼šå¯¼è‡´è§£æé”™è¯¯
# [languages.en]
# title = "Inhere's Site"
# description = "Inhere's site, blogs and project docs"

# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
# axar, css, base16-atelierdune-light
highlight_theme = "css"
bottom_footnotes = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `â€¦`, `"quote"` into `â€œcurlyâ€` etc
smart_punctuation = true
# :smile: => ğŸ˜„
render_emoji = true
# ä¸ºå¤–éƒ¨é“¾æ¥æ·»åŠ å›¾æ ‡
external_links_class = "external"
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true
# Whether to set rel="nofollow" for all external links
external_links_no_follow = true
# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
insert_anchor_links = "left"

# When set to "true", support for GitHub-style alerts, a.k.a. callouts or admonitions, is enabled in the Markdown parser.
# For example, this Markdown syntax:
#
#     > [!NOTE]
#     > alert note
#
# will result in the following generated HTML:
#
#     <blockquote class="markdown-alert-note">
#     <p>alert note</p>
#     </blockquote>
#
# where the CSS class name suffix may be `note`, `tip`, `important`, `warning`, or `caution`, depending on the alert type.
# Visual appearance depends on theme-level support; refer to your theme's documentation for more information.
github_alerts = true

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
# Whether to remove date prefixes for page path slugs.
# For example, content/posts/2016-10-08_a-post-with-dates.md => posts/a-post-with-dates
# When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
paths_keep_dates = false

[search]
index_format = "elasticlunr_javascript" # or "elasticlunr_json"
include_title = true
include_description = true
include_path = true
include_content = true

[extra]
theme_switcher = true

# This setting determines the default theme on load ("light" or "dark").
# To follow the user's OS theme, leave it empty or unset.
default_theme = ""

# Choose the colourscheme (skin) for the theme. Default is "teal".
# Skin available: blue, lavender, mint, red, sakura, teal, monochrome, lowcontrast_orange, lowcontrast_peach, lowcontrast_pink, indigo_ingot, evangelion
# See them live and learn how to create your own: https://welpo.github.io/tabi/blog/customise-tabi/#skins
# WARNING! "lowcontrast" skins, while aesthetically pleasing, may not provide optimal
# contrast (in light theme) for readability and might not be suitable for all users.
# Furthermore, low contrasting elements will affect your Google Lighthouse rating.
# All other skins have optimal contrast.
skin = "blue"

# List additional stylesheets to load site-wide.
# These stylesheets should be located in your site's `static` directory.
# Example: stylesheets = ["extra1.css", "path/extra2.css"]
# You can load a stylesheet for a single post by adding it to the [extra] section of the post's front matter, following this same format.
stylesheets = ["custom.css"]

# Show the reading time of a page.
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
show_reading_time = true
# Show the date of a page below its title.
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
show_date = true
# Determines how dates are displayed in the post listing (e.g. front page or /blog). Options:
# "date" - Show only the original date of the post (default if unset).
# "updated" - Show only the last updated date of the post. If there is no last updated date, it shows the original date.
# "both" - Show both the original date and the last updated date.
post_listing_date = "date"
# Enable Mermaid diagrams for all posts.
# Loads ~2.5MB of JavaScript.
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
mermaid = false
# Serve Mermaid JavaScript locally. Version bundled with tabi.
# If set to false, it will load the latest version from JSDelivr.
# Only relevant when `mermaid = true`.
serve_local_mermaid = true

# Quick navigation buttons.
# Adds "go up" and "go to comments" buttons on the bottom right (hidden for mobile).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
quick_navigation_buttons = true

# Custom separator used in title tag and posts metadata (between date, time to read, and tags).
separator = "â€¢"
favicon = "icons/favicon.ico"
# ç´§å‡‘æ˜¾ç¤º tags
compact_tags = true

socials = [
    { name = "github", url = "https://github.com/inhere/", icon = "github" }
]

language_name.en = "English"
language_name.zh_CN = "ä¸­æ–‡"

menu = [
    { name = "ğŸ“ Blog", url = "blog", trailing_slash = true },
    { name = "ğŸš€ Projects", url = "projects", trailing_slash = true },
    { name = "ğŸ“š Collections", url = "collections", trailing_slash = true },
    { name = "ğŸ·ï¸ Tags", url = "tags", trailing_slash = true },
    { name = "ğŸ—„ï¸ Archive", url = "archive", trailing_slash = true },
    # { name = "ğŸ± Github", url = "https://github.com/inhere", trailing_slash = false }
]

# Extra menu to show on the footer, below socials section.
footer_menu = [
    {url = "pages/about", name = "About", trailing_slash = true},
    # {url = "privacy", name = "privacy", trailing_slash = true},
    # {url = "https://tabi-stats.osc.garden", name = "site_statistics", trailing_slash = true},
    {url = "sitemap.xml", name = "Sitemap", trailing_slash = false},
]

enable_subset = true

# Git ä»“åº“é›†æˆ
remote_repository_url = "https://github.com/inhere/inhere.github.io"
remote_repository_git_platform = "auto"
remote_repository_branch = "main"
show_remote_changes = true
show_remote_source = true

[extra.author]
name = "Inhere"
avatar = "img/avatar.jpg"
