name: Test deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    # 如果你想要进一步定义触发条件、路径等，可以查看文档
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test:
    name: Test Site Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Zola Build
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_ONLY: true